apiVersion: v1
kind: Service
metadata:
  name: profile-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    service: profile
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000