apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  labels:
    service: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment
  template:
    metadata:
      labels:
        service: payment
    spec:
      containers:
      - name: payment-service
        image: hello-world
        ports:
        - containerPort: 3000
