apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
spec:
  rules:
  - http:
      paths:
      - path: /payment
        backend:
          serviceName: payment-service
          servicePort: 80
      - path: /profile
        backend:
          serviceName: profile-service
          servicePort: 80